#!/bin/bash
set -e

echo "Initializing setup..."
if [ -f /var/www/html/app/etc/env.php ]; then
  echo "It appears Magento is already installed (app/etc/config.php or app/etc/env.php exist). Exiting setup..."
  exit
fi

sudo chown -R ${USER_PHP}:${USER_PHP} /var/www/html && sudo chmod 0775 /var/www/html
mkdir -p ~/tmp
# Get source  Magento CE 2.4.2
find ~/tmp -maxdepth 0 -empty -exec php -d memory_limit=2G /usr/local/bin/composer create-project \
    --repository-url=https://repo.magento.com/ magento/project-community-edition=2.4.5 {} \;

cp -R ~/tmp/. /var/www/html/

# Symlink Composer Auth of Magento
cd /var/www/html
chmod +x /var/www/html/bin/magento
if [ ! -f /var/www/html/auth.json ]; then
    if [ ! -L /var/www/html/auth.json ]; then
        ln -s /home/web/.composer/auth.json /var/www/html/auth.json
    fi
fi
composer install

echo -n "Waiting for db"
touch database_not_ready
while [ -e database_not_ready ]; do
    mysql --host=$M2SETUP_DB_HOST --user=$M2SETUP_DB_USER --password=$M2SETUP_DB_PASSWORD \
          --execute="show tables" $M2SETUP_DB_NAME >/dev/null 2>&1 && rm database_not_ready
    sleep 2s
    echo -n "."
done
echo

echo "Running Magento 2 setup script..."
php bin/magento setup:install \
  --base-url=$M2SETUP_BASE_URL \
  --backend-frontname=$M2SETUP_BACKEND_FRONTNAME \
  --db-host=$M2SETUP_DB_HOST \
  --db-name=$M2SETUP_DB_NAME \
  --db-user=$M2SETUP_DB_USER \
  --db-password=$M2SETUP_DB_PASSWORD \
  --admin-firstname=$M2SETUP_ADMIN_FIRSTNAME \
  --admin-lastname=$M2SETUP_ADMIN_LASTNAME \
  --admin-email=$M2SETUP_ADMIN_EMAIL \
  --admin-user=$M2SETUP_ADMIN_USER \
  --admin-password=$M2SETUP_ADMIN_PASSWORD \
  --language=$M2SETUP_LANGUAGE \
  --currency=$M2SETUP_CURRENCY \
  --timezone=$M2SETUP_TIMEZONE \
  --use-rewrites=$M2SETUP_USE_REWRITES \
  --use-secure=$M2SETUP_USE_SECURE \
  --use-secure-admin=$M2SETUP_USE_SECURE_ADMIN \
  --base-url-secure=$M2SETUP_BASE_URL_SECURE \
  --search-engine=$M2SETUP_SEARCH_ENGINE \
  --elasticsearch-host=$M2SETUP_ES_HOST \
  --elasticsearch-port=$M2SETUP_ES_PORT \
  --cleanup-database

#echo "Setup Redis"
php bin/magento setup:config:set --cache-backend=redis --cache-backend-redis-db=0 \
	     --cache-backend-redis-server=$M2SETUP_REDIS_HOST 
php bin/magento setup:config:set --page-cache=redis --page-cache-redis-db=1 \
            --page-cache-redis-server=$M2SETUP_REDIS_HOST 
php bin/magento setup:config:set --session-save=redis --session-save-redis-log-level=3 \
            --session-save-redis-host=$M2SETUP_REDIS_HOST --session-save-redis-db=2 

echo "Disable module TwoFactorAuth"
php bin/magento module:disable Magento_TwoFactorAuth

# echo "Turning on developer mode.."
php bin/magento deploy:mode:set developer

echo "Add sample data"
if [ "$M2SETUP_USE_SAMPLE_DATA_STRING" == "true" ]; then
  git clone https://github.com/magento/magento2-sample-data.git \
  && cd /var/www/html/magento2-sample-data && git checkout 2.4-develop && cd /var/www/html \
  && php -f /var/www/html/magento2-sample-data/dev/tools/build-sample-data.php -- --ce-source="/var/www/html"
fi

php bin/magento setup:db:status && UPGRADE_NEEDED=0 || UPGRADE_NEEDED=1 || UPGRADE_NEEDED=2
if [[ 0 != ${UPGRADE_NEEDED} ]]; then
  php bin/magento setup:upgrade
fi

echo "Add Admin"
if [ -f $M2_ADMIN_FILE ]; then
  rm -f $M2_ADMIN_FILE
fi

declare -Ax ADMIN_USER1=${ADMIN_USER_TEST}

for admin in "${!ADMIN_USER1[@]}"; do
  ADMIN_PASSWD=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1)
  php bin/magento admin:user:create --admin-firstname=${admin} --admin-lastname='admin' --admin-user=${admin} \
                                    --admin-email=${ADMIN_USER1[$admin]} --admin-password=${ADMIN_PASSWD}
  echo "${admin} / ${ADMIN_USER1[$admin]} / ${ADMIN_PASSWD}" >> $M2_ADMIN_FILE
done

echo "Config ES & Reindex Catalog Search"
php bin/magento indexer:reindex catalogsearch_fulltext

echo "Create robots.txt"
if [ ! -f /var/www/html/robots.txt ]; then
cat <<EOF >> robots.txt
User-agent: *
Disallow: /
EOF
fi

echo "The setup script has completed execution."
echo "
===================== 🚀 Done 🚀 ===================
      Magento 2 Installed successfully!
      🌎 Admin:    "$M2SETUP_BASE_URL"admin
      👤 User:     "$M2SETUP_ADMIN_USER"
      🔑 Password: "$M2SETUP_ADMIN_PASSWORD"
===================== 🚀 Done 🚀 ==================="
